Crud cat Début
AezardSR/Le_Flamant_Bleu pull request #34
Opened 2023-04-08 14:37 UTC by Manon-POTEL

GET
ADD
Btn update + delete

2023-04-08 15:28 UTC, AezardSR commented
Pense à prendre la dernière version de la dev 
https://github.com/AezardSR/Le_Flamant_Bleu/blob/01061ab5f5a7728bb9f99a8213bad6f7207151c2/src/features/AddExercice.js#L16
ça doit ressembler à cela maintenant : 
https://github.com/AezardSR/Le_Flamant_Bleu/blob/f11c3fddce2159b5939492404d58ca6259c9af97/src/features/AddExercice.js#L15

2023-04-17 14:38 UTC, MercierCorentin requested changes, later dismissed
- [ ] Attention avec les clés étrangères, quand on delete une part, il faut mettre un message d'erreur si il reste des exercice ou des cours liés à la partie.

![image](https://user-images.githubusercontent.com/46066895/232519119-7482dcf7-0012-4149-a77b-77a3e678c541.png)

Le mieux est de lister les exercices et les cours liées à la partie dans un modal et de demander une confirmation à l'utilisateur. SI il accepte supprimer les exos et cours listés, autrement il doit lui même supprimer ces exos et cours. Il a peut-être besoin de les garder et de les changer de partie.

2023-04-20 12:34 UTC, AezardSR approved these changes

2023-04-20 12:37 UTC, AezardSR commented
> Attention avec les clés étrangères, quand on delete une part, il faut mettre un message d'erreur si il reste des exercice ou des cours liés à la partie.
> 
> ![image](https://user-images.githubusercontent.com/46066895/232519119-7482dcf7-0012-4149-a77b-77a3e678c541.png)
> 
> Le mieux est de lister les exercices et les cours liées à la partie dans un modal et de demander une confirmation à l'utilisateur. SI il accepte supprimer les exos et cours listés, autrement il doit lui même supprimer ces exos et cours. Il a peut-être besoin de les garder et de les changer de partie.

Le problème a été résolu dans l'API

2023-04-20 12:37 UTC, AezardSR approved these changes

2023-04-21 07:56 UTC, AezardSR approved these changes

2023-04-21 08:40 UTC, merged